# Generated by Django 4.2.13 on 2024-06-14 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.SmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
    ]
