# Generated by Django 4.2.13 on 2024-06-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0003_post_content_post_created_date_post_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("D", "초안"), ("P", "발행")], default="D", max_length=1
            ),
        ),
    ]
