# Generated by Django 4.2.13 on 2024-06-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0004_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ip",
            field=models.GenericIPAddressField(default="127.0.0.1"),
            preserve_default=False,
        ),
    ]
