# Generated by Django 4.2.13 on 2024-06-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0006_post_tag_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
