# Generated by Django 4.2.13 on 2024-06-28 11:25

import core.model_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile_birth_date_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=core.model_field.DatePickerField(blank=True, null=True),
        ),
    ]
