# Generated by Django 4.2.13 on 2024-06-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("D", "초안"), ("P", "발행")], default="D", max_length=1
            ),
        ),
    ]
