# Generated by Django 4.2.13 on 2024-06-06 20:53

import core.model_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_unique_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_generic", models.GenericIPAddressField(protocol="IPv4")),
                ("ip_int", core.model_field.IPv4AddressIntegerField(max_length=15)),
            ],
        ),
    ]
