# Generated by Django 4.2.13 on 2024-06-07 07:29

import core.model_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_accesslog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "is_public_ch",
                    models.CharField(
                        choices=[("Y", "예"), ("N", "아니오")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "is_public_yn",
                    core.model_field.BooleanYNField(default=False, max_length=1),
                ),
            ],
        ),
    ]
