# Generated by Django 4.2.13 on 2024-06-09 16:32

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_course_student_enrollment"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                models.F("student"),
                models.F("course"),
                django.db.models.functions.text.Lower("semester"),
                name="blog_enrollment_uniq",
            ),
        ),
    ]
