# Generated by Django 4.2.13 on 2024-06-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_posttagrelation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tag_set",
        ),
    ]
