# Generated by Django 4.2.13 on 2024-06-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_post_tag_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
